### PR TITLE
Draft: Compile on Linux

### PR DESCRIPTION
**Pull request by ASDFGamer**
This is allows the server to be compiled on linux. 

It is currently work in Progress and should help fixing Issue #8

### CODE REVIEW

**Comment by ASDFGamer** [comment]
The server is in a state that compiles and can be started from the vscode extension if it is placed in the right folder. 
But when i try to invoke it by writing some sqf code it looks like it goes into an endless loop and increases the memory usage by ~1 GB per 20 sec until my system runs out of memory because two processes used  together 30 GB.
grafik
I try to look into that but im not really optimistic, because i haven't programmed in c++ yet

**Comment by ASDFGamer** [comment]
I tried to fix the problem, but could't find a way. It isn't even always reproducible. From what I found is that it occures after VS Code is closed.

**Comment by X39** [comment]
Can you share your codebase with me please? It probably is related to a bug that, for the most part, is isolated to CDLC as of now (or at least none but those guys could reproduce that behavior)

Great job on this task 👍

**Comment by ASDFGamer** [comment]
Do you mean my SQF Codebase? The Problem occured when i added an forEach Loop over "weapons player" with the content "diag_log str _X" into the [clients/vscode/sample/needless_brackets.sqf](https://github.com/SQFvm/language-server/blob/6cc419a726409e512a87fbe62e73cc23d85127f9/clients/vscode/sample/needless_brackets.sqf). I didn't test with other Files because i belived that the Problem had nothing to do with the content of the File. The needless brackets and the uppercase _X were both without hint.

Thanks😃

**Pull request merged**
